import Head from "next/head";
import "./globals.css";
import Provider from "./provider";

export const metadata = {
  title: "ClixTV Admin",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,900;1,400;1,500;1,600;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
